const cfg=window.CODESTUDY_CONFIG||{};
const hasSupabase=Boolean(window.supabase&&cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_URL.includes('COLE_')&&!cfg.SUPABASE_ANON_KEY.includes('COLE_'));
const sb=hasSupabase?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;

const languages={
 html:{name:'HTML',icon:'🌐',desc:'Estrutura da página',topics:[
  ['Tags','Uma tag diz ao navegador o que um pedaço do conteúdo representa.','<h1>Olá!</h1>','Em HTML, <h1> é usado principalmente para:',[['a','mostrar um título'],['b','mudar a cor'],['c','fazer uma conta']], 'a','<h1> representa um título principal.'],
  ['Atributos','Atributos adicionam informações extras a uma tag.','<img src="foto.jpg" alt="Foto">','No exemplo, o atributo alt serve para:',[['a','descrever a imagem'],['b','deixar a imagem maior'],['c','criar um botão']], 'a','alt ajuda a descrever a imagem e melhora acessibilidade.'],
  ['Links','A tag <a> cria links para outras páginas.','<a href="https://exemplo.com">Abrir</a>','Qual atributo indica o destino do link?',[['a','href'],['b','src'],['c','link']], 'a','href aponta para o endereço de destino.'],
  ['Formulários','Formulários recebem dados do usuário.','<input type="text">','Qual tag é usada para receber texto simples?', [['a','input'],['b','p'],['c','section']], 'a','input cria campos de entrada.'],
  ['Semântica','Tags semânticas explicam a função do conteúdo.','<header>...</header>','Qual é um exemplo de tag semântica?', [['a','header'],['b','div'],['c','span']], 'a','header, main e footer dão significado à estrutura.'] ]},
 css:{name:'CSS',icon:'🎨',desc:'Aparência e layout',topics:[
  ['Seletores','Seletores dizem quais elementos receberão estilos.','p { color: red; }','O seletor do exemplo é:',[['a','p'],['b','red'],['c','color']], 'a','p seleciona todos os elementos <p>.'],
  ['Cores','A propriedade color muda a cor do texto.','h1 { color: purple; }','Qual propriedade muda o texto?',[['a','color'],['b','background'],['c','font']], 'a','color altera a cor do conteúdo de texto.'],
  ['Box model','Cada elemento possui conteúdo, padding, border e margin.','div { padding: 20px; }','O padding é o espaço:',[['a','entre conteúdo e borda'],['b','fora da borda'],['c','entre páginas']], 'a','padding cria espaço interno.'],
  ['Flexbox','Flexbox ajuda a alinhar elementos em uma dimensão.','.menu { display:flex; }','Qual propriedade ativa o Flexbox?',[['a','display: flex'],['b','position:flex'],['c','layout:flex']], 'a','display:flex cria um flex container.'],
  ['Grid','CSS Grid organiza páginas em linhas e colunas.','.cards { display:grid; }','Grid é útil principalmente para:',[['a','layouts em linhas e colunas'],['b','senhas'],['c','banco de dados']], 'a','Grid é excelente para layouts bidimensionais.'] ]},
 js:{name:'JavaScript',icon:'⚡',desc:'Lógica e interatividade',topics:[
  ['Variáveis','Variáveis guardam valores que o programa pode usar.','let idade = 15;','Qual comando cria uma variável que pode receber novo valor?',[['a','let'],['b','html'],['c','style']], 'a','let declara uma variável reatribuível.'],
  ['Tipos de dados','Strings são textos; números são valores numéricos.','const nome = "Luiz";','"Luiz" é um:',[['a','string'],['b','number'],['c','boolean']], 'a','Texto entre aspas é uma string.'],
  ['if / else','Condicionais deixam o programa tomar decisões.','if (idade >= 18) { ... }','Qual palavra inicia uma condição?',[['a','if'],['b','loop'],['c','case']], 'a','if testa uma condição.'],
  ['Loops','Loops repetem um bloco de código.','for (let i=0;i<3;i++) {}','Qual estrutura é usada para repetir?',[['a','for'],['b','title'],['c','color']], 'a','for é um laço de repetição.'],
  ['Funções','Funções agrupam uma tarefa que pode ser chamada depois.','function soma(a,b){ return a+b; }','Uma função serve para:',[['a','reaproveitar uma lógica'],['b','trocar o monitor'],['c','criar o banco sozinho']], 'a','Funções evitam repetir a mesma lógica.'],
  ['DOM','O DOM permite que JavaScript controle elementos HTML.','document.querySelector("h1")','Qual objeto representa a página HTML?',[['a','document'],['b','window.css'],['c','htmlFile']], 'a','document é a porta de entrada para o DOM.'] ]},
 python:{name:'Python',icon:'🐍',desc:'Sintaxe simples e poderosa',topics:[
  ['print','print mostra informações no console.','print("Olá")','Qual função mostra texto?',[['a','print'],['b','show'],['c','console']], 'a','print exibe algo no console.'],
  ['Variáveis','Python permite criar variáveis de forma simples.','idade = 15','Qual é o valor de idade?',[['a','15'],['b','"idade"'],['c','0']], 'a','idade recebe o número 15.'],
  ['if','if executa um bloco quando uma condição é verdadeira.','if idade >= 18:\n    print("adulto")','Qual palavra começa a condição?',[['a','if'],['b','then'],['c','when']], 'a','Python usa if para decisões.'],
  ['Listas','Listas guardam vários valores em ordem.','nomes = ["Ana", "Bia"]','Qual estrutura representa uma lista?',[['a','[]'],['b','{}'],['c','()']], 'a','Colchetes [] criam listas.'],
  ['Funções','def cria funções.','def soma(a,b):\n    return a+b','Qual palavra cria a função?',[['a','def'],['b','function'],['c','fn']], 'a','def define uma função em Python.'] ]},
 cpp:{name:'C++',icon:'⚙️',desc:'Performance e lógica',topics:[
  ['main','O programa geralmente começa pela função main.','int main() { return 0; }','Qual função é o ponto de entrada comum?',[['a','main'],['b','start'],['c','run']], 'a','main é o ponto de entrada tradicional.'],
  ['Variáveis','Tipos indicam o tipo de dado armazenado.','int idade = 15;','int representa:',[['a','inteiro'],['b','texto'],['c','imagem']], 'a','int é um tipo inteiro.'],
  ['if','if executa código quando uma condição é verdadeira.','if (x > 0) { }','Qual palavra inicia a decisão?',[['a','if'],['b','when'],['c','check']], 'a','if faz um teste lógico.'],
  ['for','for repete um bloco de código.','for(int i=0;i<5;i++) {}','Para que serve o for?',[['a','repetição'],['b','estilo'],['c','imagem']], 'a','for cria um laço.'],
  ['vector','std::vector guarda uma sequência dinâmica.','std::vector<int> v;','vector serve para:',[['a','armazenar vários valores'],['b','mudar CSS'],['c','criar HTML']], 'a','vector é uma coleção dinâmica.'] ]},
 java:{name:'Java',icon:'☕',desc:'Orientação a objetos',topics:[
  ['class','Classes definem estruturas e comportamentos.','class Pessoa {}','Qual palavra cria uma classe?',[['a','class'],['b','type'],['c','object']], 'a','class define uma classe.'],
  ['main','O método main é um ponto de entrada comum em aplicações Java.','public static void main(String[] args) {}','Qual método costuma iniciar o programa?',[['a','main'],['b','start'],['c','run']], 'a','main é o método de entrada tradicional.'],
  ['String','String representa texto.','String nome = "Luiz";','Qual tipo guarda texto?',[['a','String'],['b','Text'],['c','char[] only']], 'a','String é usado para textos.'],
  ['if','if testa uma condição.','if (idade >= 18) {}','Para decisão usamos:',[['a','if'],['b','when'],['c','check']], 'a','if testa expressões booleanas.'],
  ['ArrayList','ArrayList é uma lista redimensionável.','ArrayList<String> nomes = new ArrayList<>();','ArrayList serve para:',[['a','uma lista dinâmica'],['b','CSS'],['c','imagens']], 'a','ArrayList guarda uma lista dinâmica.'] ]},
 sql:{name:'SQL',icon:'🗄️',desc:'Banco de dados',topics:[
  ['SELECT','SELECT consulta dados de uma tabela.','SELECT * FROM alunos;','Qual comando consulta dados?',[['a','SELECT'],['b','GET'],['c','READ']], 'a','SELECT busca registros.'],
  ['WHERE','WHERE filtra resultados.','SELECT * FROM alunos WHERE idade >= 18;','O WHERE serve para:',[['a','filtrar'],['b','criar CSS'],['c','apagar tudo']], 'a','WHERE limita os resultados à condição.'],
  ['INSERT','INSERT adiciona registros.','INSERT INTO alunos (nome) VALUES (\'Ana\');','Qual comando adiciona dados?',[['a','INSERT'],['b','ADDROW'],['c','PUSH']], 'a','INSERT adiciona uma linha.'],
  ['UPDATE','UPDATE altera registros existentes.','UPDATE alunos SET idade=16 WHERE nome=\'Ana\';','Qual comando altera dados?',[['a','UPDATE'],['b','CHANGE'],['c','EDIT']], 'a','UPDATE modifica registros.'],
  ['DELETE','DELETE remove registros.','DELETE FROM alunos WHERE id=3;','Qual comando remove registros?',[['a','DELETE'],['b','REMOVE'],['c','DROPROW']], 'a','DELETE remove linhas; DROP é usado para objetos como tabelas.'] ]}
};

const profileModes={child:{name:'🌱 Bem simples',prompt:'Explicação bem simples: imagine que programação é ensinar um computador a seguir uma receita. Primeiro entenda a ideia e só depois decore a sintaxe.'},normal:{name:'📘 Normal',prompt:'Explicação objetiva e técnica, mas sem assumir conhecimento prévio.'},deep:{name:'🧠 Mais detalhado',prompt:'Explicação com detalhes, contexto e comparações de conceitos.'}};

let state={user:null,mode:'child',xp:0,completed:{},channel:'geral',theme:'dark',demo:false};
let messages=[];let realtimeChannel=null;

const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function key(){return `codestudy:${state.user?.id||'demo'}`}
function saveLocal(){localStorage.setItem(key(),JSON.stringify({xp:state.xp,completed:state.completed,mode:state.mode,profileName:state.user?.name||'Aluno'}));}
function loadLocal(){const d=JSON.parse(localStorage.getItem(key())||'{}');state.xp=d.xp||0;state.completed=d.completed||{};state.mode=d.mode||'child'}
function avatarText(n){return (n||'A').trim().slice(0,1).toUpperCase()}
function totalLessons(){return Object.values(languages).reduce((s,l)=>s+l.topics.length,0)}
function doneCount(){return Object.values(state.completed).filter(Boolean).length}
function overallPct(){return Math.round(doneCount()/totalLessons()*100)}
function levelInfo(){const level=Math.floor(state.xp/100)+1;const current=state.xp%100;return {level,current,pct:current,need:100-current}}
function renderHeader(title,eyebrow='COMECE POR AQUI'){$('#pageTitle').textContent=title;$('#pageEyebrow').textContent=eyebrow}
function showPage(name){$$('.page').forEach(p=>p.classList.add('hidden'));$(`#page-${name}`).classList.remove('hidden');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===name));const titles={home:['Olá!','COMECE POR AQUI'],study:['Biblioteca de estudo','APRENDA'],chat:['Comunidade','CONVERSE'],progress:['Meu progresso','ACOMPANHE'],profile:['Perfil','SUA CONTA'],lesson:['Aula','ESTUDE']};renderHeader(...(titles[name]||['CodeStudy','']));if(name==='home')renderHome();if(name==='study')renderStudy();if(name==='progress')renderProgress();}
function showLesson(lang,idx){const item=languages[lang].topics[idx];const [title,explain,code,question,opts,correct,answer]=item;const completed=!!state.completed[`${lang}:${idx}`];const mode=profileModes[state.mode];showPage('lesson');$('#lessonView').innerHTML=`<div class="lesson-view-card glass"><span class="pill purple">${languages[lang].icon} ${languages[lang].name}</span><h2>${idx+1}. ${title}</h2><p class="explain"><strong>${mode.name}:</strong> ${easyExplain(explain,title)}</p><div class="concept-box"><div class="concept"><h4>🧠 Entenda antes</h4><p>${mode.prompt}</p></div><div class="concept"><h4>✅ O que lembrar</h4><p>${answer}</p></div></div><pre class="code"><code>${escapeHTML(code)}</code></pre><div class="exercise"><h3>🧩 Agora tente</h3><p>${question}</p><div class="answer-area"><div class="lesson-actions">${opts.map(([id,t])=>`<button class="secondary option-btn" data-opt="${id}">${id.toUpperCase()}) ${t}</button>`).join('')}</div><div id="quizFeedback" class="tiny" style="margin-top:10px"></div></div><div class="exercise-actions"><button id="showAnswer" class="ghost">👀 Mostrar resposta</button><button id="completeLesson" class="primary">${completed?'✅ Concluída':'Concluir aula +20 XP'}</button></div></div></div>`;
let selected=null;$$('.option-btn').forEach(btn=>btn.onclick=()=>{selected=btn.dataset.opt;$$('.option-btn').forEach(b=>b.style.borderColor='');btn.style.borderColor='var(--accent)';if(selected===correct){$('#quizFeedback').textContent='✅ Acertou! Você entendeu o conceito.';$('#quizFeedback').style.color='var(--good)'}else{$('#quizFeedback').textContent='❌ Ainda não. Leia a explicação e tente novamente.';$('#quizFeedback').style.color='var(--bad)'}});
$('#showAnswer').onclick=()=>openDialog('answerDialog',`<h3>👀 Resposta</h3><p>${answer}</p><p><strong>Alternativa correta:</strong> ${correct.toUpperCase()}</p>`);
$('#completeLesson').onclick=()=>{if(!state.completed[`${lang}:${idx}`]){state.completed[`${lang}:${idx}`]=true;state.xp+=20;saveLocal();toast('+20 XP! Aula concluída.')}else toast('Você já concluiu esta aula.');updateAll()};
}
function easyExplain(text,title){if(state.mode==='child'){return `Pensa em <strong>${title}</strong> como uma ferramenta da sua caixa de programação. ${text} Agora compare com o exemplo abaixo e tente prever o resultado.`}if(state.mode==='deep'){return `${text} O mais importante é entender quando usar esse conceito e como ele se conecta aos anteriores. Leia o exemplo, teste pequenas mudanças e observe o que acontece.`}return text}
function escapeHTML(s){return s.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function renderHome(){const g=$('#homeLanguages');g.innerHTML='';Object.entries(languages).forEach(([id,l])=>{const done=Object.keys(state.completed).filter(k=>k.startsWith(id+':')).length;const pct=Math.round(done/l.topics.length*100);const card=document.createElement('div');card.className='lang-card';card.innerHTML=`<div class="lang-icon">${l.icon}</div><div class="lang-name">${l.name}</div><div class="lang-desc">${l.desc}</div><div class="progress-row"><span>${done}/${l.topics.length}</span><strong>${pct}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div>`;card.onclick=()=>{showPage('study');$('#languageSelect').value=id;renderStudy()};g.appendChild(card)});}
function renderStudy(){const sel=$('#languageSelect');if(!sel.options.length)sel.innerHTML=Object.entries(languages).map(([id,l])=>`<option value="${id}">${l.icon} ${l.name}</option>`).join('');const lang=sel.value||'html';$('#lessonList').innerHTML=languages[lang].topics.map(([title,explain,, ,,,],i)=>{const d=state.completed[`${lang}:${i}`];return `<article class="lesson-card ${d?'done':''}"><div class="lesson-head"><div class="lesson-num">${i+1}</div><div class="lesson-info"><h3>${title} ${d?'✅':''}</h3><p>${easyExplain(explain,title)}</p></div></div><div class="lesson-actions"><button class="primary open-lesson" data-lang="${lang}" data-idx="${i}">📖 Abrir aula</button><button class="secondary quick-answer" data-lang="${lang}" data-idx="${i}">👀 Ver resposta</button></div></article>`}).join('');$$('.open-lesson').forEach(b=>b.onclick=()=>showLesson(b.dataset.lang,+b.dataset.idx));$$('.quick-answer').forEach(b=>{b.onclick=()=>{const x=languages[b.dataset.lang].topics[+b.dataset.idx];openDialog('answerDialog',`<h3>👀 Resposta — ${x[0]}</h3><p>${x[6]}</p><p><strong>Correta:</strong> ${x[5].toUpperCase()}</p>`)}})}
function renderProgress(){const pg=$('#progressGrid');pg.innerHTML=Object.entries(languages).map(([id,l])=>{const done=Object.keys(state.completed).filter(k=>k.startsWith(id+':')).length;const pct=Math.round(done/l.topics.length*100);return `<div class="prog-card"><h3>${l.icon} ${l.name}</h3><div class="prog-top"><span>${done}/${l.topics.length} aulas</span><strong>${pct}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div></div>`}).join('');const ach=[['🌱','Primeiro passo',doneCount()>=1],['⭐','100 XP',state.xp>=100],['📚','5 aulas',doneCount()>=5],['🔥','10 aulas',doneCount()>=10],['💬','Primeira mensagem',+localStorage.getItem(`codestudy:msg:${state.user?.id||'demo'}`)||0>=1]];$('#achievements').innerHTML=ach.map(a=>`<div class="achievement ${a[2]?'unlocked':''}"><div style="font-size:24px">${a[0]}</div><strong>${a[1]}</strong><div class="tiny">${a[2]?'Desbloqueada':'Ainda bloqueada'}</div></div>`).join('')}
function updateAll(){const li=levelInfo();$('#xpTop').textContent=state.xp;$('#levelLabel').textContent=`Nível ${li.level}`;$('#levelPct').textContent=`${li.pct}%`;$('.level-ring').style.setProperty('--pct',li.pct);$('#nextLevelXP').textContent=`${li.need} XP`;$('#overallPct').textContent=`${overallPct()}%`;$('#overallBar').style.width=`${overallPct()}%`;$('#lessonsDone').textContent=doneCount();$('#exercisesDone').textContent=doneCount();$('#profileName').textContent=state.user?.name||'Aluno';$('#profileRole').textContent=state.demo?'Modo demo':'Estudante';$('#avatar').textContent=avatarText(state.user?.name);$('#profileAvatarBig').textContent=avatarText(state.user?.name);$('#profileBigName').textContent=state.user?.name||'Aluno';$('#profileBigEmail').textContent=state.user?.email||'modo demo';$('#displayNameInput').value=state.user?.name||'Aluno';$('#explainMode').value=state.mode;renderHome();renderProgress();}
async function boot(){
  setupEvents();
  if(hasSupabase){$('#backendStatus').textContent='✅ Banco conectado. Você pode criar sua conta.';$('#connectionState').textContent='online';$('#connectionState').classList.remove('offline');const {data}=await sb.auth.getSession();if(data.session) await loginSupabase(data.session)}else{$('#backendStatus').textContent='🟡 Modo demo: configure o Supabase em config.js para ter login e chat online.'}
}
async function loginSupabase(session){state.demo=false;state.user={id:session.user.id,email:session.user.email,name:session.user.user_metadata?.username||session.user.email?.split('@')[0]||'Aluno'};const {data}=await sb.from('profiles').select('*').eq('id',state.user.id).maybeSingle();if(data){state.user.name=data.username||state.user.name;state.mode=data.explain_mode||'child';state.xp=data.xp||0} else {await sb.from('profiles').insert({id:state.user.id,username:state.user.name});loadLocal()}state.active=true;document.querySelector('#authScreen').classList.add('hidden');document.querySelector('#appScreen').classList.remove('hidden');updateAll();showPage('home');await setupRealtime()}
function loginDemo(){state.demo=true;state.user={id:'demo-user',email:'demo@codestudy.local',name:'Aluno Demo'};loadLocal();document.querySelector('#authScreen').classList.add('hidden');document.querySelector('#appScreen').classList.remove('hidden');updateAll();showPage('home');loadMessagesDemo();$('#connectionState').textContent='modo demo';$('#connectionState').classList.add('offline');}
async function setupRealtime(){if(!hasSupabase)return;await loadMessagesOnline();if(realtimeChannel)sb.removeChannel(realtimeChannel);realtimeChannel=sb.channel('chat-messages').on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},async payload=>{if(payload.new.channel!==state.channel)return;const m=await hydrateMessage(payload.new);renderMessages([...messages,m]);}).subscribe();}
async function hydrateMessage(row){let name='Aluno';if(hasSupabase){const {data}=await sb.from('profiles').select('username').eq('id',row.user_id).maybeSingle();name=data?.username||name}return {id:row.id,userId:row.user_id,name,content:row.content,created_at:row.created_at}}
async function loadMessagesOnline(){if(!hasSupabase)return;const {data}=await sb.from('messages').select('*').eq('channel',state.channel).order('created_at',{ascending:true}).limit(100);messages=[];for(const row of data||[])messages.push(await hydrateMessage(row));renderMessages(messages)}
function loadMessagesDemo(){messages=JSON.parse(localStorage.getItem(`codestudy:chat:${state.channel}`)||'[]');if(!messages.length)messages=[{id:'welcome',userId:'system',name:'CodeStudy',content:'Bem-vindo ao chat! Aqui você pode conversar e tirar dúvidas. 💜',created_at:new Date().toISOString()}];renderMessages(messages)}
function renderMessages(list){const box=$('#messages');box.innerHTML='';list.forEach(m=>{const mine=m.userId===state.user?.id;const el=document.createElement('div');el.className=`message ${mine?'mine':''}`;el.innerHTML=`${mine?'':`<div class="avatar">${avatarText(m.name)}</div>`}<div class="message-bubble"><div class="message-meta"><strong>${escapeHTML(m.name)}</strong> · ${new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div><div class="message-text">${escapeHTML(m.content)}</div></div>`;box.appendChild(el)});box.scrollTop=box.scrollHeight;$('#messagesCount').textContent=list.length}
async function sendMessage(content){const clean=content.trim();if(!clean)return;if(hasSupabase&&!state.demo){const {error}=await sb.from('messages').insert({user_id:state.user.id,channel:state.channel,content:clean});if(error){toast('Não foi possível enviar.');return}}else{const list=JSON.parse(localStorage.getItem(`codestudy:chat:${state.channel}`)||'[]');list.push({id:crypto.randomUUID?.()||Date.now(),userId:state.user.id,name:state.user.name,content:clean,created_at:new Date().toISOString()});localStorage.setItem(`codestudy:chat:${state.channel}`,JSON.stringify(list));loadMessagesDemo()}localStorage.setItem(`codestudy:msg:${state.user?.id||'demo'}`,'1')}
function openDialog(id,html){if(id==='answerDialog')$('#answerContent').innerHTML=html;else $('#feedbackContent').innerHTML=html;document.getElementById(id).showModal()}
function setupEvents(){
  $$('.auth-tab').forEach(b=>b.onclick=()=>{$$('.auth-tab').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').classList.toggle('hidden',b.dataset.authTab!=='login');$('#signupForm').classList.toggle('hidden',b.dataset.authTab!=='signup')});
  $('#demoLogin').onclick=loginDemo;
  $('#loginForm').onsubmit=async e=>{e.preventDefault();if(!hasSupabase){toast('Use o modo demo ou configure o Supabase.');return}const {data,error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error)toast(error.message);else await loginSupabase(data.session)};
  $('#signupForm').onsubmit=async e=>{e.preventDefault();if(!hasSupabase){toast('Configure o Supabase primeiro.');return}const name=$('#signupName').value.trim();const {data,error}=await sb.auth.signUp({email:$('#signupEmail').value.trim(),password:$('#signupPassword').value,options:{data:{username:name}}});if(error)toast(error.message);else{toast(data.session?'Conta criada!':'Conta criada. Confira seu e-mail.');if(data.session)await loginSupabase(data.session)}};
  $$('.nav-btn').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('[data-page-jump]').forEach(b=>b.onclick=()=>showPage(b.dataset.pageJump));
  $('#languageSelect').onchange=renderStudy;
  $('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('codestudy:theme',document.body.classList.contains('light')?'light':'dark')};
  if(localStorage.getItem('codestudy:theme')==='light')document.body.classList.add('light');
  $('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');
  $$('.channel').forEach(b=>b.onclick=async()=>{ $$('.channel').forEach(x=>x.classList.toggle('active',x===b));state.channel=b.dataset.channel;$('#channelTitle').textContent='# '+state.channel;if(hasSupabase&&!state.demo)await loadMessagesOnline();else loadMessagesDemo()});
  $('#messageForm').onsubmit=async e=>{e.preventDefault();const ta=$('#messageInput');await sendMessage(ta.value);ta.value='';ta.focus()};$('#messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#messageForm').requestSubmit()}});
  $$('[data-close-dialog]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.closeDialog).close());
  $('#logoutBtn').onclick=async()=>{if(hasSupabase&&!state.demo)await sb.auth.signOut();location.reload()};
  $('#saveProfileBtn').onclick=async()=>{const n=$('#displayNameInput').value.trim()||'Aluno';state.user.name=n;state.mode=$('#explainMode').value;saveLocal();if(hasSupabase&&!state.demo){await sb.from('profiles').upsert({id:state.user.id,username:n,explain_mode:state.mode,xp:state.xp,updated_at:new Date().toISOString()})}updateAll();toast('Perfil salvo!')};
}
boot();
